### ISSUE TITLE
The system cannot find the path specified: '\\modules\\solutions\\Gym'

### ISSUE THREAD

**Issue by Rahat-Khan-Pathan** [M-S-Abeer/vjudge-to-oj#15]
When running `main.py`, it shown an error **FileNotFoundError: [WinError 3]** that says "The system cannot find the path in modules\solutions\Gym and there is no folder generated named `Gym`.

**Comment by m-s-abeer** [comment]
Could you share the whole stack-trace please if there's any?
Thanks!

**Comment by Rahat-Khan-Pathan** [comment]
$ python main.py
Loading offline problem data...
UVa Problem Data Loaded.
CodeForces Problem Data Loaded.
LightOJ Problem Data Loaded.   
Loading offline problem data...
UVa Problem Data Loaded.
CodeForces Problem Data Loaded.
LightOJ Problem Data Loaded.
Solutions downloaded and extracted.
Traceback (most recent call last):
  File "E:\Rahat Khan Pathan\vjudge-to-oj\main.py", line 23, in <module>
    vjudgeUser.downloadSubmissions()
  File "E:\Rahat Khan Pathan\vjudge-to-oj\modules\judges.py", line 100, in downloadSubmissions
    self.moveGymSolToCF()
  File "E:\Rahat Khan Pathan\vjudge-to-oj\modules\judges.py", line 127, in moveGymSolToCF
    for eachSolution in os.listdir(gymLocalSubsURL):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\Rahat Khan Pathan\\vjudge-to-oj\\modules\\solutions\\Gym'

**Comment by m-s-abeer** [comment]
@Rahat-Khan-Pathan Should be fixed now. Can you please check? Thanks!

**Comment by Rahat-Khan-Pathan** [comment]
Yes, it is working now. Thanks!

**Comment by Rajwan-Sultan** [comment]
![Screenshot 2023-02-25 012433](https://user-images.githubusercontent.com/111181255/221273006-2bd78300-068c-427d-ad00-c5df1d19f6fb.png)


I'm facing this issue
